PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2019-05-12 23:36:47.115260');
INSERT INTO django_migrations VALUES(2,'auth','0001_initial','2019-05-12 23:36:47.134188');
INSERT INTO django_migrations VALUES(3,'admin','0001_initial','2019-05-12 23:36:47.151387');
INSERT INTO django_migrations VALUES(4,'admin','0002_logentry_remove_auto_add','2019-05-12 23:36:47.166109');
INSERT INTO django_migrations VALUES(5,'admin','0003_logentry_add_action_flag_choices','2019-05-12 23:36:47.179560');
INSERT INTO django_migrations VALUES(6,'contenttypes','0002_remove_content_type_name','2019-05-12 23:36:47.207030');
INSERT INTO django_migrations VALUES(7,'auth','0002_alter_permission_name_max_length','2019-05-12 23:36:47.215933');
INSERT INTO django_migrations VALUES(8,'auth','0003_alter_user_email_max_length','2019-05-12 23:36:47.228187');
INSERT INTO django_migrations VALUES(9,'auth','0004_alter_user_username_opts','2019-05-12 23:36:47.240260');
INSERT INTO django_migrations VALUES(10,'auth','0005_alter_user_last_login_null','2019-05-12 23:36:47.254278');
INSERT INTO django_migrations VALUES(11,'auth','0006_require_contenttypes_0002','2019-05-12 23:36:47.256279');
INSERT INTO django_migrations VALUES(12,'auth','0007_alter_validators_add_error_messages','2019-05-12 23:36:47.267296');
INSERT INTO django_migrations VALUES(13,'auth','0008_alter_user_username_max_length','2019-05-12 23:36:47.279199');
INSERT INTO django_migrations VALUES(14,'auth','0009_alter_user_last_name_max_length','2019-05-12 23:36:47.291309');
INSERT INTO django_migrations VALUES(15,'auth','0010_alter_group_name_max_length','2019-05-12 23:36:47.301315');
INSERT INTO django_migrations VALUES(16,'auth','0011_update_proxy_permissions','2019-05-12 23:36:47.310210');
INSERT INTO django_migrations VALUES(17,'wagtailcore','0001_initial','2019-05-12 23:36:47.480424');
INSERT INTO django_migrations VALUES(18,'wagtailcore','0002_initial_data','2019-05-12 23:36:47.480835');
INSERT INTO django_migrations VALUES(19,'wagtailcore','0003_add_uniqueness_constraint_on_group_page_permission','2019-05-12 23:36:47.481226');
INSERT INTO django_migrations VALUES(20,'wagtailcore','0004_page_locked','2019-05-12 23:36:47.481562');
INSERT INTO django_migrations VALUES(21,'wagtailcore','0005_add_page_lock_permission_to_moderators','2019-05-12 23:36:47.481906');
INSERT INTO django_migrations VALUES(22,'wagtailcore','0006_add_lock_page_permission','2019-05-12 23:36:47.482242');
INSERT INTO django_migrations VALUES(23,'wagtailcore','0007_page_latest_revision_created_at','2019-05-12 23:36:47.482571');
INSERT INTO django_migrations VALUES(24,'wagtailcore','0008_populate_latest_revision_created_at','2019-05-12 23:36:47.482912');
INSERT INTO django_migrations VALUES(25,'wagtailcore','0009_remove_auto_now_add_from_pagerevision_created_at','2019-05-12 23:36:47.483244');
INSERT INTO django_migrations VALUES(26,'wagtailcore','0010_change_page_owner_to_null_on_delete','2019-05-12 23:36:47.483572');
INSERT INTO django_migrations VALUES(27,'wagtailcore','0011_page_first_published_at','2019-05-12 23:36:47.483920');
INSERT INTO django_migrations VALUES(28,'wagtailcore','0012_extend_page_slug_field','2019-05-12 23:36:47.484251');
INSERT INTO django_migrations VALUES(29,'wagtailcore','0013_update_golive_expire_help_text','2019-05-12 23:36:47.484602');
INSERT INTO django_migrations VALUES(30,'wagtailcore','0014_add_verbose_name','2019-05-12 23:36:47.484984');
INSERT INTO django_migrations VALUES(31,'wagtailcore','0015_add_more_verbose_names','2019-05-12 23:36:47.485373');
INSERT INTO django_migrations VALUES(32,'wagtailcore','0016_change_page_url_path_to_text_field','2019-05-12 23:36:47.485701');
INSERT INTO django_migrations VALUES(33,'wagtailcore','0017_change_edit_page_permission_description','2019-05-12 23:36:47.506881');
INSERT INTO django_migrations VALUES(34,'wagtailcore','0018_pagerevision_submitted_for_moderation_index','2019-05-12 23:36:47.523925');
INSERT INTO django_migrations VALUES(35,'wagtailcore','0019_verbose_names_cleanup','2019-05-12 23:36:47.578809');
INSERT INTO django_migrations VALUES(36,'wagtailcore','0020_add_index_on_page_first_published_at','2019-05-12 23:36:47.595773');
INSERT INTO django_migrations VALUES(37,'wagtailcore','0021_capitalizeverbose','2019-05-12 23:36:48.060452');
INSERT INTO django_migrations VALUES(38,'wagtailcore','0022_add_site_name','2019-05-12 23:36:48.077715');
INSERT INTO django_migrations VALUES(39,'wagtailcore','0023_alter_page_revision_on_delete_behaviour','2019-05-12 23:36:48.098040');
INSERT INTO django_migrations VALUES(40,'wagtailcore','0024_collection','2019-05-12 23:36:48.102638');
INSERT INTO django_migrations VALUES(41,'wagtailcore','0025_collection_initial_data','2019-05-12 23:36:48.117772');
INSERT INTO django_migrations VALUES(42,'wagtailcore','0026_group_collection_permission','2019-05-12 23:36:48.141413');
INSERT INTO django_migrations VALUES(43,'wagtailcore','0027_fix_collection_path_collation','2019-05-12 23:36:48.219761');
INSERT INTO django_migrations VALUES(44,'wagtailcore','0024_alter_page_content_type_on_delete_behaviour','2019-05-12 23:36:48.239860');
INSERT INTO django_migrations VALUES(45,'wagtailcore','0028_merge','2019-05-12 23:36:48.242441');
INSERT INTO django_migrations VALUES(46,'wagtailcore','0029_unicode_slugfield_dj19','2019-05-12 23:36:48.260637');
INSERT INTO django_migrations VALUES(47,'wagtailcore','0030_index_on_pagerevision_created_at','2019-05-12 23:36:48.279465');
INSERT INTO django_migrations VALUES(48,'wagtailcore','0031_add_page_view_restriction_types','2019-05-12 23:36:48.326945');
INSERT INTO django_migrations VALUES(49,'wagtailcore','0032_add_bulk_delete_page_permission','2019-05-12 23:36:48.346246');
INSERT INTO django_migrations VALUES(50,'wagtailcore','0033_remove_golive_expiry_help_text','2019-05-12 23:36:48.383607');
INSERT INTO django_migrations VALUES(51,'wagtailcore','0034_page_live_revision','2019-05-12 23:36:48.404046');
INSERT INTO django_migrations VALUES(52,'wagtailcore','0035_page_last_published_at','2019-05-12 23:36:48.423469');
INSERT INTO django_migrations VALUES(53,'wagtailcore','0036_populate_page_last_published_at','2019-05-12 23:36:48.442837');
INSERT INTO django_migrations VALUES(54,'wagtailcore','0037_set_page_owner_editable','2019-05-12 23:36:48.463077');
INSERT INTO django_migrations VALUES(55,'wagtailcore','0038_make_first_published_at_editable','2019-05-12 23:36:48.482898');
INSERT INTO django_migrations VALUES(56,'wagtailcore','0039_collectionviewrestriction','2019-05-12 23:36:48.522795');
INSERT INTO django_migrations VALUES(57,'wagtailcore','0040_page_draft_title','2019-05-12 23:36:48.560408');
INSERT INTO django_migrations VALUES(58,'home','0001_initial','2019-05-12 23:36:48.577252');
INSERT INTO django_migrations VALUES(59,'home','0002_create_homepage','2019-05-12 23:36:48.605633');
INSERT INTO django_migrations VALUES(60,'sessions','0001_initial','2019-05-12 23:36:48.610164');
INSERT INTO django_migrations VALUES(61,'taggit','0001_initial','2019-05-12 23:36:48.628608');
INSERT INTO django_migrations VALUES(62,'taggit','0002_auto_20150616_2121','2019-05-12 23:36:48.638042');
INSERT INTO django_migrations VALUES(63,'wagtailadmin','0001_create_admin_access_permissions','2019-05-12 23:36:48.666647');
INSERT INTO django_migrations VALUES(64,'wagtailcore','0041_group_collection_permissions_verbose_name_plural','2019-05-12 23:36:48.680831');
INSERT INTO django_migrations VALUES(65,'wagtaildocs','0001_initial','2019-05-12 23:36:48.700367');
INSERT INTO django_migrations VALUES(66,'wagtaildocs','0002_initial_data','2019-05-12 23:36:48.734661');
INSERT INTO django_migrations VALUES(67,'wagtaildocs','0003_add_verbose_names','2019-05-12 23:36:48.781261');
INSERT INTO django_migrations VALUES(68,'wagtaildocs','0004_capitalizeverbose','2019-05-12 23:36:48.871826');
INSERT INTO django_migrations VALUES(69,'wagtaildocs','0005_document_collection','2019-05-12 23:36:48.897558');
INSERT INTO django_migrations VALUES(70,'wagtaildocs','0006_copy_document_permissions_to_collections','2019-05-12 23:36:48.924171');
INSERT INTO django_migrations VALUES(71,'wagtaildocs','0005_alter_uploaded_by_user_on_delete_action','2019-05-12 23:36:48.952462');
INSERT INTO django_migrations VALUES(72,'wagtaildocs','0007_merge','2019-05-12 23:36:48.954985');
INSERT INTO django_migrations VALUES(73,'wagtaildocs','0008_document_file_size','2019-05-12 23:36:48.976170');
INSERT INTO django_migrations VALUES(74,'wagtaildocs','0009_document_verbose_name_plural','2019-05-12 23:36:48.993303');
INSERT INTO django_migrations VALUES(75,'wagtaildocs','0010_document_file_hash','2019-05-12 23:36:49.016312');
INSERT INTO django_migrations VALUES(76,'wagtailembeds','0001_initial','2019-05-12 23:36:49.024681');
INSERT INTO django_migrations VALUES(77,'wagtailembeds','0002_add_verbose_names','2019-05-12 23:36:49.103242');
INSERT INTO django_migrations VALUES(78,'wagtailembeds','0003_capitalizeverbose','2019-05-12 23:36:49.108175');
INSERT INTO django_migrations VALUES(79,'wagtailembeds','0004_embed_verbose_name_plural','2019-05-12 23:36:49.112404');
INSERT INTO django_migrations VALUES(80,'wagtailembeds','0005_specify_thumbnail_url_max_length','2019-05-12 23:36:49.120709');
INSERT INTO django_migrations VALUES(81,'wagtailforms','0001_initial','2019-05-12 23:36:49.138576');
INSERT INTO django_migrations VALUES(82,'wagtailforms','0002_add_verbose_names','2019-05-12 23:36:49.161239');
INSERT INTO django_migrations VALUES(83,'wagtailforms','0003_capitalizeverbose','2019-05-12 23:36:49.186550');
INSERT INTO django_migrations VALUES(84,'wagtailimages','0001_initial','2019-05-12 23:36:49.294995');
INSERT INTO django_migrations VALUES(85,'wagtailimages','0002_initial_data','2019-05-12 23:36:49.295550');
INSERT INTO django_migrations VALUES(86,'wagtailimages','0003_fix_focal_point_fields','2019-05-12 23:36:49.295949');
INSERT INTO django_migrations VALUES(87,'wagtailimages','0004_make_focal_point_key_not_nullable','2019-05-12 23:36:49.296325');
INSERT INTO django_migrations VALUES(88,'wagtailimages','0005_make_filter_spec_unique','2019-05-12 23:36:49.296698');
INSERT INTO django_migrations VALUES(89,'wagtailimages','0006_add_verbose_names','2019-05-12 23:36:49.297101');
INSERT INTO django_migrations VALUES(90,'wagtailimages','0007_image_file_size','2019-05-12 23:36:49.297480');
INSERT INTO django_migrations VALUES(91,'wagtailimages','0008_image_created_at_index','2019-05-12 23:36:49.297851');
INSERT INTO django_migrations VALUES(92,'wagtailimages','0009_capitalizeverbose','2019-05-12 23:36:49.298256');
INSERT INTO django_migrations VALUES(93,'wagtailimages','0010_change_on_delete_behaviour','2019-05-12 23:36:49.298633');
INSERT INTO django_migrations VALUES(94,'wagtailimages','0011_image_collection','2019-05-12 23:36:49.299062');
INSERT INTO django_migrations VALUES(95,'wagtailimages','0012_copy_image_permissions_to_collections','2019-05-12 23:36:49.299475');
INSERT INTO django_migrations VALUES(96,'wagtailimages','0013_make_rendition_upload_callable','2019-05-12 23:36:49.299925');
INSERT INTO django_migrations VALUES(97,'wagtailimages','0014_add_filter_spec_field','2019-05-12 23:36:49.300307');
INSERT INTO django_migrations VALUES(98,'wagtailimages','0015_fill_filter_spec_field','2019-05-12 23:36:49.300760');
INSERT INTO django_migrations VALUES(99,'wagtailimages','0016_deprecate_rendition_filter_relation','2019-05-12 23:36:49.301162');
INSERT INTO django_migrations VALUES(100,'wagtailimages','0017_reduce_focal_point_key_max_length','2019-05-12 23:36:49.301557');
INSERT INTO django_migrations VALUES(101,'wagtailimages','0018_remove_rendition_filter','2019-05-12 23:36:49.301985');
INSERT INTO django_migrations VALUES(102,'wagtailimages','0019_delete_filter','2019-05-12 23:36:49.302400');
INSERT INTO django_migrations VALUES(103,'wagtailimages','0020_add-verbose-name','2019-05-12 23:36:49.302832');
INSERT INTO django_migrations VALUES(104,'wagtailimages','0021_image_file_hash','2019-05-12 23:36:49.303223');
INSERT INTO django_migrations VALUES(105,'wagtailredirects','0001_initial','2019-05-12 23:36:49.332275');
INSERT INTO django_migrations VALUES(106,'wagtailredirects','0002_add_verbose_names','2019-05-12 23:36:49.376358');
INSERT INTO django_migrations VALUES(107,'wagtailredirects','0003_make_site_field_editable','2019-05-12 23:36:49.408142');
INSERT INTO django_migrations VALUES(108,'wagtailredirects','0004_set_unique_on_path_and_site','2019-05-12 23:36:49.441821');
INSERT INTO django_migrations VALUES(109,'wagtailredirects','0005_capitalizeverbose','2019-05-12 23:36:49.568815');
INSERT INTO django_migrations VALUES(110,'wagtailredirects','0006_redirect_increase_max_length','2019-05-12 23:36:49.591192');
INSERT INTO django_migrations VALUES(111,'wagtailsearch','0001_initial','2019-05-12 23:36:49.663116');
INSERT INTO django_migrations VALUES(112,'wagtailsearch','0002_add_verbose_names','2019-05-12 23:36:49.732667');
INSERT INTO django_migrations VALUES(113,'wagtailsearch','0003_remove_editors_pick','2019-05-12 23:36:49.761296');
INSERT INTO django_migrations VALUES(114,'wagtailsearch','0004_querydailyhits_verbose_name_plural','2019-05-12 23:36:49.767197');
INSERT INTO django_migrations VALUES(115,'wagtailusers','0001_initial','2019-05-12 23:36:49.794032');
INSERT INTO django_migrations VALUES(116,'wagtailusers','0002_add_verbose_name_on_userprofile','2019-05-12 23:36:49.848434');
INSERT INTO django_migrations VALUES(117,'wagtailusers','0003_add_verbose_names','2019-05-12 23:36:49.866324');
INSERT INTO django_migrations VALUES(118,'wagtailusers','0004_capitalizeverbose','2019-05-12 23:36:50.014536');
INSERT INTO django_migrations VALUES(119,'wagtailusers','0005_make_related_name_wagtail_specific','2019-05-12 23:36:50.040267');
INSERT INTO django_migrations VALUES(120,'wagtailusers','0006_userprofile_prefered_language','2019-05-12 23:36:50.059204');
INSERT INTO django_migrations VALUES(121,'wagtailusers','0007_userprofile_current_time_zone','2019-05-12 23:36:50.077819');
INSERT INTO django_migrations VALUES(122,'wagtailusers','0008_userprofile_avatar','2019-05-12 23:36:50.099983');
INSERT INTO django_migrations VALUES(123,'wagtailusers','0009_userprofile_verbose_name_plural','2019-05-12 23:36:50.117642');
INSERT INTO django_migrations VALUES(124,'wagtailimages','0001_squashed_0021','2019-05-12 23:36:50.120713');
INSERT INTO django_migrations VALUES(125,'wagtailcore','0001_squashed_0016_change_page_url_path_to_text_field','2019-05-12 23:36:50.122101');
INSERT INTO django_migrations VALUES(126,'home','0002_auto_20190512_2349','2019-05-12 23:51:11.030785');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO auth_group_permissions VALUES(1,2,1);
INSERT INTO auth_group_permissions VALUES(2,1,1);
INSERT INTO auth_group_permissions VALUES(3,2,2);
INSERT INTO auth_group_permissions VALUES(4,2,3);
INSERT INTO auth_group_permissions VALUES(5,2,4);
INSERT INTO auth_group_permissions VALUES(6,1,2);
INSERT INTO auth_group_permissions VALUES(7,1,3);
INSERT INTO auth_group_permissions VALUES(8,1,4);
INSERT INTO auth_group_permissions VALUES(9,2,5);
INSERT INTO auth_group_permissions VALUES(10,2,6);
INSERT INTO auth_group_permissions VALUES(11,2,7);
INSERT INTO auth_group_permissions VALUES(12,1,5);
INSERT INTO auth_group_permissions VALUES(13,1,6);
INSERT INTO auth_group_permissions VALUES(14,1,7);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'wagtailcore','page');
INSERT INTO django_content_type VALUES(2,'home','homepage');
INSERT INTO django_content_type VALUES(3,'wagtailadmin','admin');
INSERT INTO django_content_type VALUES(4,'wagtaildocs','document');
INSERT INTO django_content_type VALUES(5,'wagtailimages','image');
INSERT INTO django_content_type VALUES(6,'wagtailforms','formsubmission');
INSERT INTO django_content_type VALUES(7,'wagtailredirects','redirect');
INSERT INTO django_content_type VALUES(8,'wagtailembeds','embed');
INSERT INTO django_content_type VALUES(9,'wagtailusers','userprofile');
INSERT INTO django_content_type VALUES(10,'wagtailimages','rendition');
INSERT INTO django_content_type VALUES(11,'wagtailsearch','query');
INSERT INTO django_content_type VALUES(12,'wagtailsearch','querydailyhits');
INSERT INTO django_content_type VALUES(13,'wagtailcore','grouppagepermission');
INSERT INTO django_content_type VALUES(14,'wagtailcore','pagerevision');
INSERT INTO django_content_type VALUES(15,'wagtailcore','pageviewrestriction');
INSERT INTO django_content_type VALUES(16,'wagtailcore','site');
INSERT INTO django_content_type VALUES(17,'wagtailcore','collection');
INSERT INTO django_content_type VALUES(18,'wagtailcore','groupcollectionpermission');
INSERT INTO django_content_type VALUES(19,'wagtailcore','collectionviewrestriction');
INSERT INTO django_content_type VALUES(20,'taggit','tag');
INSERT INTO django_content_type VALUES(21,'taggit','taggeditem');
INSERT INTO django_content_type VALUES(22,'admin','logentry');
INSERT INTO django_content_type VALUES(23,'auth','permission');
INSERT INTO django_content_type VALUES(24,'auth','group');
INSERT INTO django_content_type VALUES(25,'auth','user');
INSERT INTO django_content_type VALUES(26,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(27,'sessions','session');
INSERT INTO django_content_type VALUES(28,'flex','flexpage');
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,3,'access_admin','Can access Wagtail admin');
INSERT INTO auth_permission VALUES(2,4,'add_document','Can add document');
INSERT INTO auth_permission VALUES(3,4,'change_document','Can change document');
INSERT INTO auth_permission VALUES(4,4,'delete_document','Can delete document');
INSERT INTO auth_permission VALUES(5,5,'add_image','Can add image');
INSERT INTO auth_permission VALUES(6,5,'change_image','Can change image');
INSERT INTO auth_permission VALUES(7,5,'delete_image','Can delete image');
INSERT INTO auth_permission VALUES(8,2,'add_homepage','Can add home page');
INSERT INTO auth_permission VALUES(9,2,'change_homepage','Can change home page');
INSERT INTO auth_permission VALUES(10,2,'delete_homepage','Can delete home page');
INSERT INTO auth_permission VALUES(11,2,'view_homepage','Can view home page');
INSERT INTO auth_permission VALUES(12,6,'add_formsubmission','Can add form submission');
INSERT INTO auth_permission VALUES(13,6,'change_formsubmission','Can change form submission');
INSERT INTO auth_permission VALUES(14,6,'delete_formsubmission','Can delete form submission');
INSERT INTO auth_permission VALUES(15,6,'view_formsubmission','Can view form submission');
INSERT INTO auth_permission VALUES(16,7,'add_redirect','Can add redirect');
INSERT INTO auth_permission VALUES(17,7,'change_redirect','Can change redirect');
INSERT INTO auth_permission VALUES(18,7,'delete_redirect','Can delete redirect');
INSERT INTO auth_permission VALUES(19,7,'view_redirect','Can view redirect');
INSERT INTO auth_permission VALUES(20,8,'add_embed','Can add embed');
INSERT INTO auth_permission VALUES(21,8,'change_embed','Can change embed');
INSERT INTO auth_permission VALUES(22,8,'delete_embed','Can delete embed');
INSERT INTO auth_permission VALUES(23,8,'view_embed','Can view embed');
INSERT INTO auth_permission VALUES(24,9,'add_userprofile','Can add user profile');
INSERT INTO auth_permission VALUES(25,9,'change_userprofile','Can change user profile');
INSERT INTO auth_permission VALUES(26,9,'delete_userprofile','Can delete user profile');
INSERT INTO auth_permission VALUES(27,9,'view_userprofile','Can view user profile');
INSERT INTO auth_permission VALUES(28,4,'view_document','Can view document');
INSERT INTO auth_permission VALUES(29,5,'view_image','Can view image');
INSERT INTO auth_permission VALUES(30,10,'add_rendition','Can add rendition');
INSERT INTO auth_permission VALUES(31,10,'change_rendition','Can change rendition');
INSERT INTO auth_permission VALUES(32,10,'delete_rendition','Can delete rendition');
INSERT INTO auth_permission VALUES(33,10,'view_rendition','Can view rendition');
INSERT INTO auth_permission VALUES(34,11,'add_query','Can add query');
INSERT INTO auth_permission VALUES(35,11,'change_query','Can change query');
INSERT INTO auth_permission VALUES(36,11,'delete_query','Can delete query');
INSERT INTO auth_permission VALUES(37,11,'view_query','Can view query');
INSERT INTO auth_permission VALUES(38,12,'add_querydailyhits','Can add Query Daily Hits');
INSERT INTO auth_permission VALUES(39,12,'change_querydailyhits','Can change Query Daily Hits');
INSERT INTO auth_permission VALUES(40,12,'delete_querydailyhits','Can delete Query Daily Hits');
INSERT INTO auth_permission VALUES(41,12,'view_querydailyhits','Can view Query Daily Hits');
INSERT INTO auth_permission VALUES(42,1,'add_page','Can add page');
INSERT INTO auth_permission VALUES(43,1,'change_page','Can change page');
INSERT INTO auth_permission VALUES(44,1,'delete_page','Can delete page');
INSERT INTO auth_permission VALUES(45,1,'view_page','Can view page');
INSERT INTO auth_permission VALUES(46,13,'add_grouppagepermission','Can add group page permission');
INSERT INTO auth_permission VALUES(47,13,'change_grouppagepermission','Can change group page permission');
INSERT INTO auth_permission VALUES(48,13,'delete_grouppagepermission','Can delete group page permission');
INSERT INTO auth_permission VALUES(49,13,'view_grouppagepermission','Can view group page permission');
INSERT INTO auth_permission VALUES(50,14,'add_pagerevision','Can add page revision');
INSERT INTO auth_permission VALUES(51,14,'change_pagerevision','Can change page revision');
INSERT INTO auth_permission VALUES(52,14,'delete_pagerevision','Can delete page revision');
INSERT INTO auth_permission VALUES(53,14,'view_pagerevision','Can view page revision');
INSERT INTO auth_permission VALUES(54,15,'add_pageviewrestriction','Can add page view restriction');
INSERT INTO auth_permission VALUES(55,15,'change_pageviewrestriction','Can change page view restriction');
INSERT INTO auth_permission VALUES(56,15,'delete_pageviewrestriction','Can delete page view restriction');
INSERT INTO auth_permission VALUES(57,15,'view_pageviewrestriction','Can view page view restriction');
INSERT INTO auth_permission VALUES(58,16,'add_site','Can add site');
INSERT INTO auth_permission VALUES(59,16,'change_site','Can change site');
INSERT INTO auth_permission VALUES(60,16,'delete_site','Can delete site');
INSERT INTO auth_permission VALUES(61,16,'view_site','Can view site');
INSERT INTO auth_permission VALUES(62,17,'add_collection','Can add collection');
INSERT INTO auth_permission VALUES(63,17,'change_collection','Can change collection');
INSERT INTO auth_permission VALUES(64,17,'delete_collection','Can delete collection');
INSERT INTO auth_permission VALUES(65,17,'view_collection','Can view collection');
INSERT INTO auth_permission VALUES(66,18,'add_groupcollectionpermission','Can add group collection permission');
INSERT INTO auth_permission VALUES(67,18,'change_groupcollectionpermission','Can change group collection permission');
INSERT INTO auth_permission VALUES(68,18,'delete_groupcollectionpermission','Can delete group collection permission');
INSERT INTO auth_permission VALUES(69,18,'view_groupcollectionpermission','Can view group collection permission');
INSERT INTO auth_permission VALUES(70,19,'add_collectionviewrestriction','Can add collection view restriction');
INSERT INTO auth_permission VALUES(71,19,'change_collectionviewrestriction','Can change collection view restriction');
INSERT INTO auth_permission VALUES(72,19,'delete_collectionviewrestriction','Can delete collection view restriction');
INSERT INTO auth_permission VALUES(73,19,'view_collectionviewrestriction','Can view collection view restriction');
INSERT INTO auth_permission VALUES(74,20,'add_tag','Can add Tag');
INSERT INTO auth_permission VALUES(75,20,'change_tag','Can change Tag');
INSERT INTO auth_permission VALUES(76,20,'delete_tag','Can delete Tag');
INSERT INTO auth_permission VALUES(77,20,'view_tag','Can view Tag');
INSERT INTO auth_permission VALUES(78,21,'add_taggeditem','Can add Tagged Item');
INSERT INTO auth_permission VALUES(79,21,'change_taggeditem','Can change Tagged Item');
INSERT INTO auth_permission VALUES(80,21,'delete_taggeditem','Can delete Tagged Item');
INSERT INTO auth_permission VALUES(81,21,'view_taggeditem','Can view Tagged Item');
INSERT INTO auth_permission VALUES(82,22,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(83,22,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(84,22,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(85,22,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(86,23,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(87,23,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(88,23,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(89,23,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(90,24,'add_group','Can add group');
INSERT INTO auth_permission VALUES(91,24,'change_group','Can change group');
INSERT INTO auth_permission VALUES(92,24,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(93,24,'view_group','Can view group');
INSERT INTO auth_permission VALUES(94,25,'add_user','Can add user');
INSERT INTO auth_permission VALUES(95,25,'change_user','Can change user');
INSERT INTO auth_permission VALUES(96,25,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(97,25,'view_user','Can view user');
INSERT INTO auth_permission VALUES(98,26,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(99,26,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(100,26,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(101,26,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(102,27,'add_session','Can add session');
INSERT INTO auth_permission VALUES(103,27,'change_session','Can change session');
INSERT INTO auth_permission VALUES(104,27,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(105,27,'view_session','Can view session');
INSERT INTO auth_permission VALUES(106,28,'add_flexpage','Can add Flex Page');
INSERT INTO auth_permission VALUES(107,28,'change_flexpage','Can change Flex Page');
INSERT INTO auth_permission VALUES(108,28,'delete_flexpage','Can delete Flex Page');
INSERT INTO auth_permission VALUES(109,28,'view_flexpage','Can view Flex Page');
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_name" varchar(150) NOT NULL);
INSERT INTO auth_user VALUES(1,'pbkdf2_sha256$150000$M5omYuwUIypG$sJq57nR1PobbTSdZz0r1NDZLYWfGlqw0chudsI2r5Ko=','2019-05-13 15:21:25.749207',1,'bradrice','','bradrice1@gmail.com',1,1,'2019-05-12 23:40:37.836039','');
INSERT INTO auth_user VALUES(2,'pbkdf2_sha256$150000$Bz5XlpK5HQnS$A+anF6aRAX2lAfjKazPskjeqn3uWn7FGxFpK07J4DGA=','2019-05-16 12:55:15.238009',1,'pam','Pam','pmiller450@zoominternet.net',0,1,'2019-05-16 00:48:46.927445','Miller');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
INSERT INTO auth_group VALUES(1,'Moderators');
INSERT INTO auth_group VALUES(2,'Editors');
CREATE TABLE IF NOT EXISTS "wagtailcore_site" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hostname" varchar(255) NOT NULL, "port" integer NOT NULL, "is_default_site" bool NOT NULL, "root_page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "site_name" varchar(255) NULL);
INSERT INTO wagtailcore_site VALUES(2,'localhost',80,1,3,NULL);
CREATE TABLE IF NOT EXISTS "wagtailcore_collection" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "path" varchar(255) NOT NULL UNIQUE, "depth" integer unsigned NOT NULL CHECK ("depth" >= 0), "numchild" integer unsigned NOT NULL CHECK ("numchild" >= 0), "name" varchar(255) NOT NULL);
INSERT INTO wagtailcore_collection VALUES(1,'0001',1,0,'Root');
CREATE TABLE IF NOT EXISTS "wagtailcore_groupcollectionpermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(1,1,2,2);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(2,1,1,2);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(3,1,2,3);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(4,1,1,3);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(5,1,2,5);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(6,1,1,5);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(7,1,2,6);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(8,1,1,6);
CREATE TABLE IF NOT EXISTS "wagtailcore_pagerevision" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "submitted_for_moderation" bool NOT NULL, "content_json" text NOT NULL, "approved_go_live_at" datetime NULL, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "created_at" datetime NOT NULL);
INSERT INTO wagtailcore_pagerevision VALUES(1,0,'{"pk": 3, "path": "00010001", "depth": 2, "numchild": 0, "title": "Home", "draft_title": "Home", "slug": "home", "content_type": 2, "live": true, "has_unpublished_changes": false, "url_path": "/home/", "owner": null, "seo_title": "", "show_in_menus": false, "search_description": "", "go_live_at": null, "expire_at": null, "expired": false, "locked": false, "first_published_at": null, "last_published_at": null, "latest_revision_created_at": null, "live_revision": null, "banner_title": "Medina Diversity Project", "left_col": "<p>left col</p>", "right_col": "<p>right col</p>", "banner_image": 1}',NULL,3,1,'2019-05-13 00:07:17.250125');
INSERT INTO wagtailcore_pagerevision VALUES(2,0,'{"pk": 3, "path": "00010001", "depth": 2, "numchild": 0, "title": "Home", "draft_title": "Home", "slug": "home", "content_type": 2, "live": true, "has_unpublished_changes": true, "url_path": "/home/", "owner": null, "seo_title": "", "show_in_menus": false, "search_description": "", "go_live_at": null, "expire_at": null, "expired": false, "locked": false, "first_published_at": null, "last_published_at": null, "latest_revision_created_at": "2019-05-13T00:07:17.250Z", "live_revision": null, "banner_title": "Medina Diversity Project", "left_col": "<h2><b>Community Conversation on Race</b></h2><p><b>Monday, February 25, 2019 - 7:00 \u2013 8:30 PM</b></p><p>Medina First Christian Church<br/>4797 Sharon-Copley Rd.<br/>Medina, OH 44256</p>", "right_col": "<h3><b>The Medina Diversity Project is organized to embrace and promote social, cultural, and economic diversity throughout Medina County.</b></h3><p><i>The mission of the Medina Diversity Project will be accomplished through these objectives:</i></p><ol><li>Raise awareness in the community through conversations on race and diversity with members of the community and community leaders.</li><li>Advocate to increase employment opportunities for minorities in both the public (specifically in our schools, police departments, County and City governments) and the private sector.</li><li>Advocate to ensure that every child in Medina County, regardless of race or income level, feels safe and accepted in their environment and has the opportunity to participate in sports or other extracurricular activities in the schools and the community.</li></ol>", "banner_image": 1}',NULL,3,1,'2019-05-13 00:08:30.949864');
INSERT INTO wagtailcore_pagerevision VALUES(3,0,'{"pk": 3, "path": "00010001", "depth": 2, "numchild": 0, "title": "Home", "draft_title": "Home", "slug": "home", "content_type": 2, "live": true, "has_unpublished_changes": true, "url_path": "/home/", "owner": null, "seo_title": "", "show_in_menus": false, "search_description": "", "go_live_at": null, "expire_at": null, "expired": false, "locked": false, "first_published_at": null, "last_published_at": null, "latest_revision_created_at": "2019-05-13T00:08:30.949Z", "live_revision": null, "banner_title": "Medina Diversity Project", "left_col": "<h2><b>Community Conversation on Race</b></h2><p><b>Monday, February 25, 2019 - 7:00 \u2013 8:30 PM</b></p><p>Medina First Christian Church<br/>4797 Sharon-Copley Rd.<br/>Medina, OH 44256</p>", "right_col": "<h3><b>The Medina Diversity Project is organized to embrace and promote social, cultural, and economic diversity throughout Medina County.</b></h3><p><i>The mission of the Medina Diversity Project will be accomplished through these objectives:</i></p><ol><li>Raise awareness in the community through conversations on race and diversity with members of the community and community leaders.</li><li>Advocate to increase employment opportunities for minorities in both the public (specifically in our schools, police departments, County and City governments) and the private sector.</li><li>Advocate to ensure that every child in Medina County, regardless of race or income level, feels safe and accepted in their environment and has the opportunity to participate in sports or other extracurricular activities in the schools and the community.</li></ol>", "banner_image": 1}',NULL,3,1,'2019-05-13 00:08:42.411499');
INSERT INTO wagtailcore_pagerevision VALUES(4,0,'{"pk": 3, "path": "00010001", "depth": 2, "numchild": 0, "title": "Home", "draft_title": "Home", "slug": "home", "content_type": 2, "live": true, "has_unpublished_changes": false, "url_path": "/home/", "owner": null, "seo_title": "", "show_in_menus": false, "search_description": "", "go_live_at": null, "expire_at": null, "expired": false, "locked": false, "first_published_at": "2019-05-13T00:08:42.428Z", "last_published_at": "2019-05-13T00:08:42.428Z", "latest_revision_created_at": "2019-05-13T00:08:42.411Z", "live_revision": 3, "banner_title": "Medina Diversity Project", "left_col": "<h2><b>Community Conversation on Race</b></h2><p><b>Monday, February 25, 2019 - 7:00 \u2013 8:30 PM</b></p><p>Medina First Christian Church<br/>4797 Sharon-Copley Rd.<br/>Medina, OH 44256</p>", "right_col": "<h3><b>The Medina Diversity Project is organized to embrace and promote social, cultural, and economic diversity throughout Medina County.</b></h3><p><i>The mission of the Medina Diversity Project will be accomplished through these objectives:</i></p><ol><li>Raise awareness in the community through conversations on race and diversity with members of the community and community leaders.</li><li>Advocate to increase employment opportunities for minorities in both the public (specifically in our schools, police departments, County and City governments) and the private sector.</li><li>Advocate to ensure that every child in Medina County, regardless of race or income level, feels safe and accepted in their environment and has the opportunity to participate in sports or other extracurricular activities in the schools and the community.</li></ol>", "banner_image": 1}',NULL,3,1,'2019-05-13 00:12:19.923143');
CREATE TABLE IF NOT EXISTS "wagtailcore_pageviewrestriction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "restriction_type" varchar(20) NOT NULL, "password" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "wagtailcore_grouppagepermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_type" varchar(20) NOT NULL);
INSERT INTO wagtailcore_grouppagepermission VALUES(1,1,1,'add');
INSERT INTO wagtailcore_grouppagepermission VALUES(2,1,1,'edit');
INSERT INTO wagtailcore_grouppagepermission VALUES(3,1,1,'publish');
INSERT INTO wagtailcore_grouppagepermission VALUES(4,2,1,'add');
INSERT INTO wagtailcore_grouppagepermission VALUES(5,2,1,'edit');
INSERT INTO wagtailcore_grouppagepermission VALUES(6,1,1,'lock');
CREATE TABLE IF NOT EXISTS "wagtailcore_collectionviewrestriction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "restriction_type" varchar(20) NOT NULL, "password" varchar(255) NOT NULL, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtailcore_collectionviewrestriction_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "collectionviewrestriction_id" integer NOT NULL REFERENCES "wagtailcore_collectionviewrestriction" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtailcore_pageviewrestriction_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "pageviewrestriction_id" integer NOT NULL REFERENCES "wagtailcore_pageviewrestriction" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtailcore_page" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "path" varchar(255) NOT NULL UNIQUE, "depth" integer unsigned NOT NULL CHECK ("depth" >= 0), "numchild" integer unsigned NOT NULL CHECK ("numchild" >= 0), "title" varchar(255) NOT NULL, "slug" varchar(255) NOT NULL, "live" bool NOT NULL, "has_unpublished_changes" bool NOT NULL, "url_path" text NOT NULL, "seo_title" varchar(255) NOT NULL, "show_in_menus" bool NOT NULL, "search_description" text NOT NULL, "go_live_at" datetime NULL, "expire_at" datetime NULL, "expired" bool NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "locked" bool NOT NULL, "latest_revision_created_at" datetime NULL, "first_published_at" datetime NULL, "live_revision_id" integer NULL REFERENCES "wagtailcore_pagerevision" ("id") DEFERRABLE INITIALLY DEFERRED, "last_published_at" datetime NULL, "draft_title" varchar(255) NOT NULL);
INSERT INTO wagtailcore_page VALUES(1,'0001',1,1,'Root','root',1,0,'/','',0,'',NULL,NULL,0,1,NULL,0,NULL,NULL,NULL,NULL,'Root');
INSERT INTO wagtailcore_page VALUES(3,'00010001',2,0,'Home','home',1,0,'/home/','',0,'',NULL,NULL,0,2,NULL,0,'2019-05-13 00:12:19.923143','2019-05-13 00:08:42.428796',4,'2019-05-13 00:12:19.942651','Home');
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO django_session VALUES('lbxli6m06bq1rud1nlp6cm3j0y5ta2au','OTY2YWJkNzlmMzA5ODEyMjU0YzVlMDVkOGIwNGJjOTRjMTI4ZTBkYjp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiI1NTFmODJhODhlOTRmMWZjYTQ5MTMwYjVjNTljYWNkMDkxMDBiZDRiIiwid2FndGFpbC1wcmV2aWV3LTMiOlsiY3NyZm1pZGRsZXdhcmV0b2tlbj1iUDZIdjRCbzg0OEpmUHQzU0RobDZoWU11ZFhTWUJsMnIyYmlvRXg3RHlYYmVEcEEwdm9yUXdDWmNZcnRvVG1UJm5leHQ9JnRpdGxlPUhvbWUmYmFubmVyX3RpdGxlPU1lZGluYStEaXZlcnNpdHkrUHJvamVjdCZiYW5uZXJfaW1hZ2U9MSZsZWZ0X2NvbD0lN0IlMjJibG9ja3MlMjIlM0ElNUIlN0IlMjJrZXklMjIlM0ElMjJiM3JhbyUyMiUyQyUyMnRleHQlMjIlM0ElMjJDb21tdW5pdHkrQ29udmVyc2F0aW9uK29uK1JhY2UlMjIlMkMlMjJ0eXBlJTIyJTNBJTIyaGVhZGVyLXR3byUyMiUyQyUyMmRlcHRoJTIyJTNBMCUyQyUyMmlubGluZVN0eWxlUmFuZ2VzJTIyJTNBJTVCJTdCJTIyb2Zmc2V0JTIyJTNBMCUyQyUyMmxlbmd0aCUyMiUzQTMwJTJDJTIyc3R5bGUlMjIlM0ElMjJCT0xEJTIyJTdEJTVEJTJDJTIyZW50aXR5UmFuZ2VzJTIyJTNBJTVCJTVEJTJDJTIyZGF0YSUyMiUzQSU3QiU3RCU3RCUyQyU3QiUyMmtleSUyMiUzQSUyMnZ6ZWU4JTIyJTJDJTIydGV4dCUyMiUzQSUyMk1vbmRheSUyQytGZWJydWFyeSsyNSUyQysyMDE5Ky0rNyUzQTAwKyVFMiU4MCU5Mys4JTNBMzArUE0lMjIlMkMlMjJ0eXBlJTIyJTNBJTIydW5zdHlsZWQlMjIlMkMlMjJkZXB0aCUyMiUzQTAlMkMlMjJpbmxpbmVTdHlsZVJhbmdlcyUyMiUzQSU1QiU3QiUyMm9mZnNldCUyMiUzQTAlMkMlMjJsZW5ndGglMjIlM0E0MiUyQyUyMnN0eWxlJTIyJTNBJTIyQk9MRCUyMiU3RCU1RCUyQyUyMmVudGl0eVJhbmdlcyUyMiUzQSU1QiU1RCUyQyUyMmRhdGElMjIlM0ElN0IlN0QlN0QlMkMlN0IlMjJrZXklMjIlM0ElMjJlY2w0YyUyMiUyQyUyMnRleHQlMjIlM0ElMjJNZWRpbmErRmlyc3QrQ2hyaXN0aWFuK0NodXJjaCU1Q240Nzk3K1NoYXJvbi1Db3BsZXkrUmQuJTVDbk1lZGluYSUyQytPSCs0NDI1NiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJ1bnN0eWxlZCUyMiUyQyUyMmRlcHRoJTIyJTNBMCUyQyUyMmlubGluZVN0eWxlUmFuZ2VzJTIyJTNBJTVCJTVEJTJDJTIyZW50aXR5UmFuZ2VzJTIyJTNBJTVCJTVEJTJDJTIyZGF0YSUyMiUzQSU3QiU3RCU3RCU1RCUyQyUyMmVudGl0eU1hcCUyMiUzQSU3QiU3RCU3RCZyaWdodF9jb2w9JTdCJTIyYmxvY2tzJTIyJTNBJTVCJTdCJTIya2V5JTIyJTNBJTIyaW1ta2wlMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyVGhlK01lZGluYStEaXZlcnNpdHkrUHJvamVjdCtpcytvcmdhbml6ZWQrdG8rZW1icmFjZSthbmQrcHJvbW90ZStzb2NpYWwlMkMrY3VsdHVyYWwlMkMrYW5kK2Vjb25vbWljK2RpdmVyc2l0eSt0aHJvdWdob3V0K01lZGluYStDb3VudHkuJTIyJTJDJTIydHlwZSUyMiUzQSUyMmhlYWRlci10aHJlZSUyMiUyQyUyMmRlcHRoJTIyJTNBMCUyQyUyMmlubGluZVN0eWxlUmFuZ2VzJTIyJTNBJTVCJTdCJTIyb2Zmc2V0JTIyJTNBMCUyQyUyMmxlbmd0aCUyMiUzQTEzMSUyQyUyMnN0eWxlJTIyJTNBJTIyQk9MRCUyMiU3RCU1RCUyQyUyMmVudGl0eVJhbmdlcyUyMiUzQSU1QiU1RCUyQyUyMmRhdGElMjIlM0ElN0IlN0QlN0QlMkMlN0IlMjJrZXklMjIlM0ElMjI5M2dtcSUyMiUyQyUyMnRleHQlMjIlM0ElMjJUaGUrbWlzc2lvbitvZit0aGUrTWVkaW5hK0RpdmVyc2l0eStQcm9qZWN0K3dpbGwrYmUrYWNjb21wbGlzaGVkK3Rocm91Z2grdGhlc2Urb2JqZWN0aXZlcyUzQSUyMiUyQyUyMnR5cGUlMjIlM0ElMjJ1bnN0eWxlZCUyMiUyQyUyMmRlcHRoJTIyJTNBMCUyQyUyMmlubGluZVN0eWxlUmFuZ2VzJTIyJTNBJTVCJTdCJTIyb2Zmc2V0JTIyJTNBMCUyQyUyMmxlbmd0aCUyMiUzQTkwJTJDJTIyc3R5bGUlMjIlM0ElMjJJVEFMSUMlMjIlN0QlNUQlMkMlMjJlbnRpdHlSYW5nZXMlMjIlM0ElNUIlNUQlMkMlMjJkYXRhJTIyJTNBJTdCJTdEJTdEJTJDJTdCJTIya2V5JTIyJTNBJTIyM2ZnbmolMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyUmFpc2UrYXdhcmVuZXNzK2luK3RoZStjb21tdW5pdHkrdGhyb3VnaCtjb252ZXJzYXRpb25zK29uK3JhY2UrYW5kK2RpdmVyc2l0eSt3aXRoK21lbWJlcnMrb2YrdGhlK2NvbW11bml0eSthbmQrY29tbXVuaXR5K2xlYWRlcnMuJTIyJTJDJTIydHlwZSUyMiUzQSUyMm9yZGVyZWQtbGlzdC1pdGVtJTIyJTJDJTIyZGVwdGglMjIlM0EwJTJDJTIyaW5saW5lU3R5bGVSYW5nZXMlMjIlM0ElNUIlNUQlMkMlMjJlbnRpdHlSYW5nZXMlMjIlM0ElNUIlNUQlMkMlMjJkYXRhJTIyJTNBJTdCJTdEJTdEJTJDJTdCJTIya2V5JTIyJTNBJTIydnRxNWYlMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyQWR2b2NhdGUrdG8raW5jcmVhc2UrZW1wbG95bWVudCtvcHBvcnR1bml0aWVzK2ZvcittaW5vcml0aWVzK2luK2JvdGgrdGhlK3B1YmxpYyslMjhzcGVjaWZpY2FsbHkraW4rb3VyK3NjaG9vbHMlMkMrcG9saWNlK2RlcGFydG1lbnRzJTJDK0NvdW50eSthbmQrQ2l0eStnb3Zlcm5tZW50cyUyOSthbmQrdGhlK3ByaXZhdGUrc2VjdG9yLiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJvcmRlcmVkLWxpc3QtaXRlbSUyMiUyQyUyMmRlcHRoJTIyJTNBMCUyQyUyMmlubGluZVN0eWxlUmFuZ2VzJTIyJTNBJTVCJTVEJTJDJTIyZW50aXR5UmFuZ2VzJTIyJTNBJTVCJTVEJTJDJTIyZGF0YSUyMiUzQSU3QiU3RCU3RCUyQyU3QiUyMmtleSUyMiUzQSUyMm83dHc1JTIyJTJDJTIydGV4dCUyMiUzQSUyMkFkdm9jYXRlK3RvK2Vuc3VyZSt0aGF0K2V2ZXJ5K2NoaWxkK2luK01lZGluYStDb3VudHklMkMrcmVnYXJkbGVzcytvZityYWNlK29yK2luY29tZStsZXZlbCUyQytmZWVscytzYWZlK2FuZCthY2NlcHRlZCtpbit0aGVpcitlbnZpcm9ubWVudCthbmQraGFzK3RoZStvcHBvcnR1bml0eSt0bytwYXJ0aWNpcGF0ZStpbitzcG9ydHMrb3Irb3RoZXIrZXh0cmFjdXJyaWN1bGFyK2FjdGl2aXRpZXMraW4rdGhlK3NjaG9vbHMrYW5kK3RoZStjb21tdW5pdHkuJTIyJTJDJTIydHlwZSUyMiUzQSUyMm9yZGVyZWQtbGlzdC1pdGVtJTIyJTJDJTIyZGVwdGglMjIlM0EwJTJDJTIyaW5saW5lU3R5bGVSYW5nZXMlMjIlM0ElNUIlNUQlMkMlMjJlbnRpdHlSYW5nZXMlMjIlM0ElNUIlNUQlMkMlMjJkYXRhJTIyJTNBJTdCJTdEJTdEJTVEJTJDJTIyZW50aXR5TWFwJTIyJTNBJTdCJTdEJTdEJnNsdWc9aG9tZSZzZW9fdGl0bGU9JnNlYXJjaF9kZXNjcmlwdGlvbj0mZ29fbGl2ZV9hdD0mZXhwaXJlX2F0PSIsMTU1NzcwNjMzNC42ODA1MTEyXX0=','2019-05-27 00:12:14.694676');
INSERT INTO django_session VALUES('5aodc1hs4ijdcthd851xrt1swn3y7nhy','MTUzN2RlNGRkNjI4MDdlYjc0NGE4ZjljODJjMDM5MjYzYWU2ODVjZTp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiI1NTFmODJhODhlOTRmMWZjYTQ5MTMwYjVjNTljYWNkMDkxMDBiZDRiIn0=','2019-05-27 14:00:19.756842');
CREATE TABLE IF NOT EXISTS "taggit_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "taggit_taggeditem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" integer NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "tag_id" integer NOT NULL REFERENCES "taggit_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtaildocs_document" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "uploaded_by_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "file_size" integer unsigned NULL CHECK ("file_size" >= 0), "file_hash" varchar(40) NOT NULL);
CREATE TABLE IF NOT EXISTS "wagtailembeds_embed" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "url" varchar(200) NOT NULL, "max_width" smallint NULL, "type" varchar(10) NOT NULL, "html" text NOT NULL, "title" text NOT NULL, "author_name" text NOT NULL, "provider_name" text NOT NULL, "width" integer NULL, "height" integer NULL, "last_updated" datetime NOT NULL, "thumbnail_url" varchar(255) NULL);
CREATE TABLE IF NOT EXISTS "wagtailforms_formsubmission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "form_data" text NOT NULL, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "submit_time" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "wagtailimages_image" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "created_at" datetime NOT NULL, "focal_point_x" integer unsigned NULL CHECK ("focal_point_x" >= 0), "focal_point_y" integer unsigned NULL CHECK ("focal_point_y" >= 0), "focal_point_width" integer unsigned NULL CHECK ("focal_point_width" >= 0), "focal_point_height" integer unsigned NULL CHECK ("focal_point_height" >= 0), "uploaded_by_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "file_size" integer unsigned NULL CHECK ("file_size" >= 0), "collection_id" integer NOT NULL REFERENCES "wagtailcore_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "file_hash" varchar(40) NOT NULL);
INSERT INTO wagtailimages_image VALUES(1,'dan-gold-696882-unsplash.jpg','original_images/dan-gold-696882-unsplash_pQA1Azr.jpg',3677,300,'2019-05-13 00:06:59.547150',NULL,NULL,NULL,NULL,1,589075,1,'3334f28e4e4e5825e60d90e1f464b3db7d4b63f6');
CREATE TABLE IF NOT EXISTS "wagtailimages_rendition" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file" varchar(100) NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "focal_point_key" varchar(16) NOT NULL, "filter_spec" varchar(255) NOT NULL, "image_id" integer NOT NULL REFERENCES "wagtailimages_image" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO wagtailimages_rendition VALUES(1,'images/dan-gold-696882-unsplash_pQA1Azr.max-165x165.jpg',165,13,'','max-165x165',1);
INSERT INTO wagtailimages_rendition VALUES(2,'images/dan-gold-696882-unsplash_pQA1Azr.2e16d0ba.fill-3677x300.jpg',3677,300,'2e16d0ba','fill-3677x300',1);
CREATE TABLE IF NOT EXISTS "wagtailredirects_redirect" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "old_path" varchar(255) NOT NULL, "is_permanent" bool NOT NULL, "redirect_page_id" integer NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "site_id" integer NULL REFERENCES "wagtailcore_site" ("id") DEFERRABLE INITIALLY DEFERRED, "redirect_link" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "wagtailsearch_query" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "query_string" varchar(255) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "wagtailsearch_querydailyhits" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "hits" integer NOT NULL, "query_id" integer NOT NULL REFERENCES "wagtailsearch_query" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtailsearch_editorspick" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sort_order" integer NULL, "description" text NOT NULL, "query_id" integer NOT NULL REFERENCES "wagtailsearch_query" ("id") DEFERRABLE INITIALLY DEFERRED, "page_id" integer NOT NULL REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "wagtailusers_userprofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "submitted_notifications" bool NOT NULL, "approved_notifications" bool NOT NULL, "rejected_notifications" bool NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "preferred_language" varchar(10) NOT NULL, "current_time_zone" varchar(40) NOT NULL, "avatar" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "home_homepage" ("page_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED, "banner_image_id" integer NULL REFERENCES "wagtailimages_image" ("id") DEFERRABLE INITIALLY DEFERRED, "banner_title" varchar(100) NULL, "left_col" text NOT NULL, "right_col" text NOT NULL);
INSERT INTO home_homepage VALUES(3,1,'Medina Diversity Project','<h2><b>Community Conversation on Race</b></h2><p><b>Monday, February 25, 2019 - 7:00 – 8:30 PM</b></p><p>Medina First Christian Church<br/>4797 Sharon-Copley Rd.<br/>Medina, OH 44256</p>','<h3><b>The Medina Diversity Project is organized to embrace and promote social, cultural, and economic diversity throughout Medina County.</b></h3><p><i>The mission of the Medina Diversity Project will be accomplished through these objectives:</i></p><ol><li>Raise awareness in the community through conversations on race and diversity with members of the community and community leaders.</li><li>Advocate to increase employment opportunities for minorities in both the public (specifically in our schools, police departments, County and City governments) and the private sector.</li><li>Advocate to ensure that every child in Medina County, regardless of race or income level, feels safe and accepted in their environment and has the opportunity to participate in sports or other extracurricular activities in the schools and the community.</li></ol>');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('django_migrations',126);
INSERT INTO sqlite_sequence VALUES('django_admin_log',0);
INSERT INTO sqlite_sequence VALUES('django_content_type',28);
INSERT INTO sqlite_sequence VALUES('auth_permission',109);
INSERT INTO sqlite_sequence VALUES('auth_user',2);
INSERT INTO sqlite_sequence VALUES('auth_group',2);
INSERT INTO sqlite_sequence VALUES('wagtailcore_site',2);
INSERT INTO sqlite_sequence VALUES('wagtailcore_collection',1);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pagerevision',4);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pageviewrestriction',0);
INSERT INTO sqlite_sequence VALUES('wagtailcore_grouppagepermission',6);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pageviewrestriction_groups',0);
INSERT INTO sqlite_sequence VALUES('wagtailcore_page',3);
INSERT INTO sqlite_sequence VALUES('auth_group_permissions',14);
INSERT INTO sqlite_sequence VALUES('wagtailcore_groupcollectionpermission',8);
INSERT INTO sqlite_sequence VALUES('wagtaildocs_document',0);
INSERT INTO sqlite_sequence VALUES('wagtailembeds_embed',0);
INSERT INTO sqlite_sequence VALUES('wagtailforms_formsubmission',0);
INSERT INTO sqlite_sequence VALUES('wagtailredirects_redirect',0);
INSERT INTO sqlite_sequence VALUES('wagtailsearch_editorspick',0);
INSERT INTO sqlite_sequence VALUES('wagtailusers_userprofile',0);
INSERT INTO sqlite_sequence VALUES('wagtailimages_image',1);
INSERT INTO sqlite_sequence VALUES('wagtailimages_rendition',2);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "wagtailcore_site_hostname_port_2c626d70_uniq" ON "wagtailcore_site" ("hostname", "port");
CREATE INDEX "wagtailcore_site_hostname_96b20b46" ON "wagtailcore_site" ("hostname");
CREATE INDEX "wagtailcore_site_root_page_id_e02fb95c" ON "wagtailcore_site" ("root_page_id");
CREATE UNIQUE INDEX "wagtailcore_groupcollectionpermission_group_id_collection_id_permission_id_a21cefe9_uniq" ON "wagtailcore_groupcollectionpermission" ("group_id", "collection_id", "permission_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_collection_id_5423575a" ON "wagtailcore_groupcollectionpermission" ("collection_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_group_id_05d61460" ON "wagtailcore_groupcollectionpermission" ("group_id");
CREATE INDEX "wagtailcore_groupcollectionpermission_permission_id_1b626275" ON "wagtailcore_groupcollectionpermission" ("permission_id");
CREATE INDEX "wagtailcore_pagerevision_submitted_for_moderation_c682e44c" ON "wagtailcore_pagerevision" ("submitted_for_moderation");
CREATE INDEX "wagtailcore_pagerevision_page_id_d421cc1d" ON "wagtailcore_pagerevision" ("page_id");
CREATE INDEX "wagtailcore_pagerevision_user_id_2409d2f4" ON "wagtailcore_pagerevision" ("user_id");
CREATE INDEX "wagtailcore_pagerevision_created_at_66954e3b" ON "wagtailcore_pagerevision" ("created_at");
CREATE INDEX "wagtailcore_pageviewrestriction_page_id_15a8bea6" ON "wagtailcore_pageviewrestriction" ("page_id");
CREATE UNIQUE INDEX "wagtailcore_grouppagepermission_group_id_page_id_permission_type_0898bdf8_uniq" ON "wagtailcore_grouppagepermission" ("group_id", "page_id", "permission_type");
CREATE INDEX "wagtailcore_grouppagepermission_group_id_fc07e671" ON "wagtailcore_grouppagepermission" ("group_id");
CREATE INDEX "wagtailcore_grouppagepermission_page_id_710b114a" ON "wagtailcore_grouppagepermission" ("page_id");
CREATE INDEX "wagtailcore_collectionviewrestriction_collection_id_761908ec" ON "wagtailcore_collectionviewrestriction" ("collection_id");
CREATE UNIQUE INDEX "wagtailcore_collectionviewrestriction_groups_collectionviewrestriction_id_group_id_988995ae_uniq" ON "wagtailcore_collectionviewrestriction_groups" ("collectionviewrestriction_id", "group_id");
CREATE INDEX "wagtailcore_collectionviewrestriction_groups_collectionviewrestriction_id_47320efd" ON "wagtailcore_collectionviewrestriction_groups" ("collectionviewrestriction_id");
CREATE INDEX "wagtailcore_collectionviewrestriction_groups_group_id_1823f2a3" ON "wagtailcore_collectionviewrestriction_groups" ("group_id");
CREATE UNIQUE INDEX "wagtailcore_pageviewrestriction_groups_pageviewrestriction_id_group_id_d23f80bb_uniq" ON "wagtailcore_pageviewrestriction_groups" ("pageviewrestriction_id", "group_id");
CREATE INDEX "wagtailcore_pageviewrestriction_groups_pageviewrestriction_id_f147a99a" ON "wagtailcore_pageviewrestriction_groups" ("pageviewrestriction_id");
CREATE INDEX "wagtailcore_pageviewrestriction_groups_group_id_6460f223" ON "wagtailcore_pageviewrestriction_groups" ("group_id");
CREATE INDEX "wagtailcore_page_slug_e7c11b8f" ON "wagtailcore_page" ("slug");
CREATE INDEX "wagtailcore_page_content_type_id_c28424df" ON "wagtailcore_page" ("content_type_id");
CREATE INDEX "wagtailcore_page_owner_id_fbf7c332" ON "wagtailcore_page" ("owner_id");
CREATE INDEX "wagtailcore_page_first_published_at_2b5dd637" ON "wagtailcore_page" ("first_published_at");
CREATE INDEX "wagtailcore_page_live_revision_id_930bd822" ON "wagtailcore_page" ("live_revision_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "taggit_taggeditem_object_id_e2d7d1df" ON "taggit_taggeditem" ("object_id");
CREATE INDEX "taggit_taggeditem_content_type_id_9957a03c" ON "taggit_taggeditem" ("content_type_id");
CREATE INDEX "taggit_taggeditem_tag_id_f4f5b767" ON "taggit_taggeditem" ("tag_id");
CREATE INDEX "taggit_taggeditem_content_type_id_object_id_196cc965_idx" ON "taggit_taggeditem" ("content_type_id", "object_id");
CREATE INDEX "wagtaildocs_document_uploaded_by_user_id_17258b41" ON "wagtaildocs_document" ("uploaded_by_user_id");
CREATE INDEX "wagtaildocs_document_collection_id_23881625" ON "wagtaildocs_document" ("collection_id");
CREATE UNIQUE INDEX "wagtailembeds_embed_url_max_width_8a2922d8_uniq" ON "wagtailembeds_embed" ("url", "max_width");
CREATE INDEX "wagtailforms_formsubmission_page_id_e48e93e7" ON "wagtailforms_formsubmission" ("page_id");
CREATE UNIQUE INDEX "wagtailimages_rendition_image_id_filter_spec_focal_point_key_323c8fe0_uniq" ON "wagtailimages_rendition" ("image_id", "filter_spec", "focal_point_key");
CREATE INDEX "wagtailimages_image_created_at_86fa6cd4" ON "wagtailimages_image" ("created_at");
CREATE INDEX "wagtailimages_image_uploaded_by_user_id_5d73dc75" ON "wagtailimages_image" ("uploaded_by_user_id");
CREATE INDEX "wagtailimages_image_collection_id_c2f8af7e" ON "wagtailimages_image" ("collection_id");
CREATE INDEX "wagtailimages_rendition_filter_spec_1cba3201" ON "wagtailimages_rendition" ("filter_spec");
CREATE INDEX "wagtailimages_rendition_image_id_3e1fd774" ON "wagtailimages_rendition" ("image_id");
CREATE UNIQUE INDEX "wagtailredirects_redirect_old_path_site_id_783622d7_uniq" ON "wagtailredirects_redirect" ("old_path", "site_id");
CREATE INDEX "wagtailredirects_redirect_old_path_bb35247b" ON "wagtailredirects_redirect" ("old_path");
CREATE INDEX "wagtailredirects_redirect_redirect_page_id_b5728a8f" ON "wagtailredirects_redirect" ("redirect_page_id");
CREATE INDEX "wagtailredirects_redirect_site_id_780a0e1e" ON "wagtailredirects_redirect" ("site_id");
CREATE UNIQUE INDEX "wagtailsearch_querydailyhits_query_id_date_1dd232e6_uniq" ON "wagtailsearch_querydailyhits" ("query_id", "date");
CREATE INDEX "wagtailsearch_querydailyhits_query_id_2185994b" ON "wagtailsearch_querydailyhits" ("query_id");
CREATE INDEX "wagtailsearch_editorspick_query_id_c6eee4a0" ON "wagtailsearch_editorspick" ("query_id");
CREATE INDEX "wagtailsearch_editorspick_page_id_28cbc274" ON "wagtailsearch_editorspick" ("page_id");
CREATE INDEX "home_homepage_banner_image_id_ccdec6a2" ON "home_homepage" ("banner_image_id");
COMMIT;
